---
title: "Shiny App Project Documentation"
output: html_document
---

This is the documentation for my Shiny application project submission built for the Coursera *Developing Data Products* course.  

The project requirement (copied from the Coursera project page) is to:

1. Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user will need to get started using your application.
2. Deploy the application on Rstudio's shiny server
3. Share the application link by pasting it into the text box below
4. Share your server.R and ui.R code on github

The application must include the following:

1. Some form of input (widget: textbox, radio button, checkbox, ...)
2. Some operation on the ui input in sever.R
3. Some reactive output displayed as a result of server calculations
4. You must also include enough documentation so that a novice user could use your application.
5. The documentation should be at the Shiny website itself. Do not post to an external link.

###Project Overview

For this project, I built a simple Shiny app based on the `mtcars` dataset that allows a user to see the miles per gallon (MPG) they could expect to obtain from a new car, based on their selection of up to three variables: Transmission type (standard or automatic), Engine size (numer of cylinders), and Gross horsepower.  By way of introduction, the `mtcars` dataset is data that was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models).

For demonstration purposes, I built a relatively simple PLS predictive model (code below) designed to estimate MPG when the Shiny app user modifies selections of Transmission types, Cylinder configurations, and overall Horsepower along a 0-500 slider.  I understand that this is not an enormously extensible model, given the relatively small size of the `mtcars` dataset (only 32 observations), but it does demonstrate the functionality of Shiny. For what it's worth, the predicted values generated by this PLS model do compare well with the actual test values, with a correlation close to 1 (`0.9648836`) and a very low p-value (`0.0001054`). 

###How to Use
In order to use the Shiny App, simply make selections for all three vehicle attributes and watch to see the Projected MPG fluctuate!

##ENJOY

```{r eval=FALSE}
#load the mtcars dataset
data(mtcars)
mtcars<-mtcars
#load caret package and partition the data
library(caret)
inTrain<-createDataPartition(y=mtcars$mpg,p=0.7,list=FALSE)
train<-mtcars[inTrain,]
test<-mtcars[-inTrain,]

#set the tune control to do repeated cross validation 5 times
ctrl<-trainControl(method="repeatedcv",
                   repeats=5)
#build a Partial Least Squares model and test it out
pls<-train(mpg~.,
          data=train,
          method="pls",
          tuneLength=15,
          tuneControl=ctrl,
          preProc=c("center","scale"))
plspred<-predict(pls,newdata=test)
#confirm that the resulting predictions are statistically similar to the test set
result<-data.frame(cbind(plspred,test$mpg))
names(result)<-c("pred","test")
cor.test(result$pred,result$test)

#build a dummy dataframe with the mean values for every variable, 
#then we can change each variable one at a time within the ultimate Shiny app to get new mpg predictions
pick<-as.data.frame.list(colMeans(mtcars))

#generate a predicted MPG value
predict(pls,pick)
```
